name: quiz_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  firebase_auth: ^4.6.3
  line_awesome_flutter: ^2.0.0
  flutter_otp_text_field: ^1.1.1
  cloud_firestore: ^4.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/splash.jpg
     - assets/images/
     - assets/images/gIcon.png
  #   - images/a_dot_ham.jpeg - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
