// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJlz8ZvKCi4Utu_E2p5IQygmOMe-eaf-U',
    appId: '1:219537245461:web:1fee0abfdfe95eb1de151c',
    messagingSenderId: '219537245461',
    projectId: 'quiz-app-d074d',
    authDomain: 'quiz-app-d074d.firebaseapp.com',
    storageBucket: 'quiz-app-d074d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrJQIeoJmP64v7Z3fQMgttRCkZotwKS6M',
    appId: '1:219537245461:android:edc3944d63990690de151c',
    messagingSenderId: '219537245461',
    projectId: 'quiz-app-d074d',
    storageBucket: 'quiz-app-d074d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADZGK3chEOGXWjpBmEupQuZuvRSAFh7f0',
    appId: '1:219537245461:ios:12f8acf376316f26de151c',
    messagingSenderId: '219537245461',
    projectId: 'quiz-app-d074d',
    storageBucket: 'quiz-app-d074d.appspot.com',
    iosClientId: '219537245461-f9pvre7i99fkavnbhftj57nt9hqg7c8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADZGK3chEOGXWjpBmEupQuZuvRSAFh7f0',
    appId: '1:219537245461:ios:eaaad7398a5de4f2de151c',
    messagingSenderId: '219537245461',
    projectId: 'quiz-app-d074d',
    storageBucket: 'quiz-app-d074d.appspot.com',
    iosClientId: '219537245461-8fmk8jugqhc76291gg19212ah8e6u6ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
